### PR TITLE
Declare variable, fixed use of volatile keyword

### PR DESCRIPTION
**Pull request by rajat2004**
This fixes compilation errors on UE 4.24 (clang-8)
https://github.com/microsoft/AirSim/pull/2472#issuecomment-605379156

### CODE REVIEW

**Comment by rajat2004** [comment]
Wait, I'm not getting any images currently

**Comment by ironclownfish** [comment]
@rajat2004 
Thanks. simGetImages() needs a small fix before merging. simGetImage() will return images in the meantime if you'd like to check it out.

**Comment by rajat2004** [comment]
@ironclownfish It's crashing for me without even starting the Image benchmark script (only sometimes, but starting the script with either option crashes it) - https://github.com/microsoft/AirSim/pull/2472#issuecomment-605389786

**Comment by rajat2004** [comment]
Closing as the problem has been fixed

**Pull request closed without merging**
